name: My Workflow

on:
  push:
    branches:
      - developer
jobs:
  build:
    if: contains(github.event.head_commit.message, 'build') && ${{ steps.check_lowercase.outputs.lowercase }} == 'true'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Echo a simple statement
      run: echo "Hello, world!"

    - name: Print GitHub username and commit message
      run: |
        echo "GitHub Username: $GITHUB_ACTOR"
        echo "Commit Message: $(git log --format=%B -n 1)"

     - name: Check commit message format
        run: |
          commit_message=$(git log --format=%B -n 1 $GITHUB_SHA)
          if [[ "$commit_message" != "${commit_message,,}" ]]; then
            echo "Commit message must be lowercase."
            exit 1
          fi
